### ISSUE TITLE
Is there a package for AirRouter ?

### ISSUE THREAD

**Issue by soamz** [richb-hanover/openwrt-docs#1]
We need WRT package for AirRouter UBNT. 
Possible ?

**Comment by richb-hanover** [comment]
Thanks for the note. This github repo is a (sort of) clone of the OpenWrt wiki as of May 2105. Nothing in these files should be regarded as true.

But... You want to check out the Table of Hardware (ToH) on the OpenWrt site. It's at http://wiki.openwrt.org/toh/start

And good news - there appears to be a current build for it. To work the table, enter "airrouter" in the (white) Model field, and press Return.

The "Device Page" column gives specifics of what people have done to make the software work on the AirRouter.

If you have questions, you should post them to the OpenWrt Forums, at https://forum.openwrt.org/viewforum.php?id=10
