### ISSUE TITLE
Compiled version

### ISSUE THREAD

**Issue by johanbar** [richb-hanover/openwrt-docs#2]
Hi there

Do you have a compiled version of http://ftp.dlink.ru/pub/ADSL/GPL_source_code/RU_DSL-2500U/ please ready to flash to the 2500U - mine is still going strong but needs an upgrade ?

Thanks allot

**Comment by richb-hanover** [comment]
Hello,

This is an old copy of the OpenWrt documentation from 2015. It is not current, and I am not familiar with your specific router.

You might have better luck asking on the forum at https://forum.openwrt.org/viewtopic.php?id=50322

Best regards
